### ISSUE TITLE
Fails to restart server

### ISSUE THREAD

**Issue by Boba194230** [Steveplays28/restart-server#21]
I'm not sure why but whenever I try to restart with the command it doesn't work. Heres the log. 
[00:50:53] [Server thread/INFO]: [38;5;11m[Restart Server] Restarting server...[0m
[00:50:53] [Server thread/INFO]: [Restart Server] java.io.IOException: Cannot run program "cmd": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at java.base/java.lang.Runtime.exec(Runtime.java:594)
	at java.base/java.lang.Runtime.exec(Runtime.java:418)
	at java.base/java.lang.Runtime.exec(Runtime.java:315)
	at io.github.steveplays28.restartserver.commands.RestartCommand.execute(RestartCommand.java:34)
	at io.github.steveplays28.restartserver.commands.RestartCommand.lambda$register$0(RestartCommand.java:19)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at net.minecraft.class_2170.method_9249(class_2170.java:287)
	at net.minecraft.class_2170.method_44252(class_2170.java:280)
	at net.minecraft.class_3176.method_13941(class_3176.java:299)
	at net.minecraft.class_3176.method_3813(class_3176.java:284)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 15 more

[00:50:53] [Server thread/INFO]: [38;5;9m[Restart Server] Server restart failed.[0m

**Comment by Steveplays28** [comment]
Hi Boba,

what OS do you run?
You need to do some manual setup, point to a command launcher and/or terminal, as well as a restart command.
Did you configure the restart file to point to your custom (re)start file?

Thanks for checking out the mod.

**Comment by Boba194230** [comment]
Nope I didn't sorry, didn’t know I had to. I have the server running on a headless Debian distro so tbh I’m not exactly sure how to set it up but I’ll see what I can do

**Comment by Steveplays28** [comment]
All good, if you take a look at the wiki you can find some more details and examples. The config also contains comments explaining the options.

Let me know if you need any more help!

**Comment by Steveplays28** [comment]
Closing, if you have any more questions, feel free to ask.
